name: Docker Build Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repository kodunu indir
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Image Build
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/php-rest-api-microservice:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/php-rest-api-microservice:${{ github.sha }} \
            .

      - name: Docker Hub Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-rest-api-microservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-rest-api-microservice:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: AWS EC2 Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/php-api

            # Eski çalışan image'ın tag'ini kaydet
            OLD_TAG=$(docker inspect --format='{{.Config.Image}}' php_api_prod | cut -d':' -f2)

            # Yeni commit'in image'ını kullan
            export IMAGE_TAG=${{ github.sha }}

            # Yeni image'ı indir ve çalıştır
            docker compose -f docker-compose.prod.yml pull web
            docker compose -f docker-compose.prod.yml up -d --force-recreate web

            # Uygulamanın açılmasını bekle
            sleep 20

            # Health durumunu kontrol et
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' php_api_prod)

            if [ "$STATUS" = "healthy" ]; then
              echo "✅ Deployment başarılı."
            else
              echo "❌ Deployment başarısız! Rollback başlatılıyor..."

              export IMAGE_TAG=$OLD_TAG

              docker compose -f docker-compose.prod.yml up -d --force-recreate web

              exit 1
            fi

            docker image prune -f
